const characters = [
    {   "name": "제론",
        "hanzul": "달빛을 등에 지고, 이곳에 서 있으니.",
        "num": "01",
        "role": "⚔️ 돌격형",
        "area": "🌸 아스하리아",
        "hp": 32,
        "weapon": "달빛 검",
        "story": "달빛처럼 푸르고 하얀 검기를 다루는 검사. 그의 검이 지나간 자리는 달처럼 은은하고 초승달과 같은 검흔이 남는다.",
        "img": "agents/chr01.png",
        "img2": "agents/chr01-1.png",
        "img3": "agents/chr01-2.png",
        "author": "트작",

        "skill1": "달빛 베기",
        "skill1b": "(10s)",
        "skill1a": "전방으로 빠르게 돌진하고, 경로에 있는 모든 적을 공격한다",
        "skill2": "월광",
        "skill2b": "(20s)",
        "skill2a": "주변에 있는 모든 적을 공격한다",
        "skill3": "달빛 정화",
        "skill3b": "(30s)",
        "skill3a": "자신에게 <span style='color:#FFFF00;'>신속, 속공, 재생</span>을 부여하고 디버프를 제거한다",
        "ultimate": "달 가르기",
        "ultimateb": "<{65s}>",
        "ultimatea": "전방을 공격하고, 달빛 베기의 쿨타임을 초기화한다. 이 스킬로 적 처치 시, 달 가르기의 쿨타임을 초기화한다",
        "passive": "",
        "passivea": "",

    },{ "name": "베르세르크",
        "hanzul": "의뢰는 선금부터 받고 시작하지.",
        "num": "02",
        "role": "⚔️ 돌격형",
        "area": "📜 알데리온",
        "hp": 40,
        "weapon": "으스러진 둔기",
        "story": "알데리온 뒷세계에서 붉은 선혈빛 도끼로 유명한 용병. 의뢰의 댓가는 무겁지만 실력만큼은 확실하기로 유명한 실력자.",
        "img": "agents/chr02.png",
        "img2": "agents/chr02-1.png",
        "img3": "agents/chr02-2.png",
        "author": "Original",

        "skill1": "내려찍기",
        "skill1b": "(8s)",
        "skill1a": "전방을 공격하고 <span style='color:red;'>기절</span>을 부여한다.",
        "skill2": "돌파",
        "skill2b": "(15s)",
        "skill2a": "전방으로 돌진하고 적을 공격한다.",
        "skill3": "광폭화",
        "skill3b": "(30s)",
        "skill3a": "자신에게 <span style='color:#FFFF00;'>힘</span>과 <span style='color:#FFFF00;'>저항</span>을 부여한다.",
        "ultimate": "분쇄",
        "ultimateb": "<{90s}>",
        "ultimatea": "선딜레이 이후, 전방을 광역으로 공격하며 적을 <span style='color:red;'>기절</span>시키고 에어본시킨다.",
        "passive": "후회",
        "passivea": "기본 이동 속도가 소폭 감소한다. 이 패시브는 제거되거나 무효화되지 않는다.",

    },{ "name": "가람",
        "hanzul": "고요한 물에도 파동을 일으키면 거세게 일어나는 법이야.",
        "num": "03",
        "role": "⚔️ 돌격형",
        "area": "🌸 아스하리아",
        "hp": 30,
        "weapon": "청류",
        "story": "물의 기운을 조절하고 내보내며 물의 도술로 사원을 수호하는 무녀. 조용하고 섬세한 성격으로 고요한 물과 같은 인상을 준다.",
        "img": "agents/chr03.png",
        "img2": "agents/chr03-1.png",
        "img3": "agents/chr03-2.png",
        "author": "로하",

        "skill1": "급류",
        "skill1b": "(12s)",
        "skill1a": "전방으로 돌진하며 적에게 피해를 준다",
        "skill2": "새벽 이슬",
        "skill2b": "(25s)",
        "skill2a": "자신 주변에 이슬방울 보호막을 형성해 2초 동안 <span style='color:#FFFF00;'>무적</span> 상태가 된다",
        "skill3": "폭포수",
        "skill3b": "(25s)",
        "skill3a": "선딜레이 이후, 전방 구역에 있는 적에게 피해를 주고 <span style='color:red;'>피해 망상</span>을 부여한다",
        "ultimate": "여울",
        "ultimateb": "<{80s}>",
        "ultimatea": "선딜레이 이후, 주변으로 강한 물살의 물을 내보내 적을 공격하고 에어본을 부여하며, <span style='color:red;'>피해 망상</span>을 부여한다",
        "passive": "",
        "passivea": "",

    },{ "name": "하린",
        "hanzul": "꽃잎처럼 사뿐히, 벚꽃처럼 붉게.",
        "num": "04",
        "role": "⚔️ 돌격형",
        "area": "🌸 아스하리아",
        "hp": 24,
        "weapon": "화류염도(花流镰刀)",
        "story": "사쿠라지마 소속 최후의 닌자. 그녀의 무기가 지나간 자리에는 벚꽃처럼 보이는 핏자국이 남는다. 벚꽃잎이 내려앉는 것처럼 고요하고 가볍게.",
        "img": "agents/chr04.png",
        "img2": "agents/chr04-1.png",
        "img3": "agents/chr04-2.png",
        "author": "이루렌",

        "skill1": "영화참(櫻花斬)",
        "skill1b": "(5s / 7🌸)",
        "skill1a": "주변 적을 공격한 후, 활공한다. 적 공격 시, <span style='color:#FF6090;'>꽃잎</span> 3개가 소환된다",
        "skill2": "비화투척(飛花投擲)",
        "skill2b": "(7s / 10🌸)",
        "skill2a": "전방에 부채꼴로 수리검을 5개 투척한다. 수리검은 적 적중시, 피해를 입히고 <span style='color:#FF6090;'>꽃잎</span> 1개를 소환한다",
        "skill3": "비화낙인(飛花烙印)",
        "skill3b": "(10s / 15🌸)",
        "skill3a": "전방으로 낙인 수리검을 투척하고 <span style='color:#FFFF00;'>은신</span>을 획득한다. 낙인 수리검은 적에게 표식을 부여한다. 스킬 재사용 시, 표식이 부여된 적에게 돌진하며 피해를 준다",
        "ultimate": "비화첨참(飛花鐮斬)",
        "ultimateb": "<{70s}>",
        "ultimatea": "전방으로 도약한 뒤, 전방을 낫으로 찍어 광역으로 공격한다. 이후, 4방향으로 해당 위치에 낫이 날라오며 적을 공격한다. 낫은 적중 시, 개당 <span style='color:#FF6090;'>꽃잎</span>을 2개 소환한다",
        "passive": "화반(花瓣)",
        "passivea": "초당 1씩 꽃잎🌸을 획득하며, 특정 스킬에 소모된다 (최대 30)<br>떨어진 꽃잎에 다가갈 시 꽃잎을 획득하며, 적 처치 시, 꽃잎을 15개 획득한다.",

    },{ "name": "솔리스",
        "hanzul": "빛으로 어둠을 걷어낼게요.",
        "num": "05",
        "role": "🔥 저격형",
        "area": "📜 알데리온",
        "hp": "24",
        "weapon": "솔라 스태프 ㅡ 발화",
        "story": "알데리온 왕실 마법학교 수석 졸업자. 태양과 빛을 다루는 마법이 주 특기이며, 따뜻하고 상냥한 마음씨를 가지고 있는 소녀이다.",
        "img": "agents/chr05.png",
        "img2": "agents/chr05-1.png",
        "img3": "agents/chr05-2.png",
        "author": "세토",

        "skill1": "플레어",
        "skill1b": "(6s)",
        "skill1a": "전방으로 화염구를 소환한다. 화염구는 적에게 피해와 <span style='color:red;'>화상</span>을 부여한다",
        "skill2": "흑점 폭발",
        "skill2b": "(25s)",
        "skill2a": "선딜레이 후, 전방 구역을 폭발하며 적에게 피해와 <span style='color:red;'>화상</span>을 부여한다",
        "skill3": "채층",
        "skill3b": "(35s)",
        "skill3a": "자신에게 일정 시간 동안 채층 보호막을 부여한다. 채층 보호막은 피해를 입을 시, 1회에 한해 피해를 80% 경감 시키고, 주변 적을 공격하며 <span style='color:red;'>화상</span>을 부여한다",
        "ultimate": "화염풍",
        "ultimateb": "<{80s}>",
        "ultimatea": "전방 구역을 지속적으로 공격한 뒤, 폭발하며 적에게 광역으로 피해와 <span style='color:red;'>화상</span>을 부여한다",
        "passive": "",
        "passivea": "",

    },{ "name": "템페스트",
        "hanzul": "바람을 타고 가뿐하게!",
        "num": "06",
        "role": "🔥 저격형",
        "area": "🌿 실바네르",
        "hp": "26",
        "weapon": "바람의 활",
        "story": "실바네르 깊은 숲속의 사냥꾼. 바람처럼 가뿐한 몸놀림과 뛰어난 활솜씨로 인정받고 있다. 활기차고 발랄한 소녀로 엘프족의 피를 이었다.",
        "img": "agents/chr06.png",
        "img2": "agents/chr06-1.png",
        "img3": "agents/chr06-2.png",
        "author": "트작",

        "skill1": "칼날 바람",
        "skill1b": "(8s)",
        "skill1a": "전방으로 적들을 관통하는 칼바람을 발사한다",
        "skill2": "순풍",
        "skill2b": "(25s)",
        "skill2a": "다음 일반 공격이 광역으로 적에게 피해를 주고, 넉백시키는 폭풍 화살로 변경된다",
        "skill3": "폭풍",
        "skill3b": "(35s)",
        "skill3a": "선딜레이 이후, 주변 적을 넉백시키고 <span style='color:red;'>구속</span>을 부여한다",
        "ultimate": "태풍",
        "ultimateb": "<{85s}>",
        "ultimatea": "태풍 화살을 장착한다. 스킬 재사용시, 선딜레이 이후 적들을 끌어당긴 뒤, 폭발하는 태풍 화살을 발사한다",
        "passive": "활공",
        "passivea": "공중에서 웅크리기 시, 낙하 속도가 감소하며, 활공 거리가 증가한다",

    },{ "name": "이시스",
        "hanzul": "총알 한발로 널 심판한다.",
        "num": "07",
        "role": "🔥 저격형",
        "area": "📜 알데리온",
        "hp": "24",
        "weapon": "전술 나이프",
        "story": "알데리온 제 1왕국군 소속 저격수. 그녀는 저격기사단의 단장직을 임하고 있다. 뛰어난 사격 솜씨로 왕국에서 인정받는 군인 중 하나.",
        "img": "agents/chr07.png",
        "img2": "agents/chr07-1.png",
        "img3": "agents/chr07-2.png",
        "author": "준우",

        "skill1": "난사 모듈",
        "skill1b": "(보조 무기 / <span style='color:#910700;'>탄환</span> 3 소모)",
        "skill1a": "중거리에서 총알을 3번 발사한다",
        "skill2": "사격 모듈",
        "skill2b": "(보조 무기 / <span style='color:#910700;'>탄환</span> 3 소모)",
        "skill2a": "선딜레이 후, 초장거리에서 총알을 발사하며 적을 저격한다",
        "skill3": "도주",
        "skill3b": "(35s)",
        "skill3a": "전방으로 적을 <span style='color:red;'>기절</span>시키는 투사체를 투척한다. 적중 성공 시, 자신에게 <span style='color:#FFFF00;'>신속</span>을 부여한다",
        "ultimate": "일점사",
        "ultimateb": "<{85s}>",
        "ultimatea": "모든 <span style='color:#910700;'>탄환</span>을 소모하며, 소모한 <span style='color:#910700;'>탄환</span>만큼 전방으로 난사한다. 적 처치시, 모든 <span style='color:#910700;'>탄환</span>을 즉시 재장전한다",
        "passive": "탄환: 이시스",
        "passivea": "<span style='color:#910700;'>탄환</span> 30발이 지급되며, 특정 스킬에 소모된다. 모두 사용 시, 8초 후 재장전한다",

    },{ "name": "바티",
        "hanzul": "음악은 때때로 우리를 치유하죠.",
        "num": "08",
        "role": "⭐ 지원형",
        "area": "🌿 실바네르",
        "hp": "30",
        "weapon": "하프",
        "story": "엘프의 피를 이은 음유시인. 그의 노래는 특별한 힘이 있어 누군가를 치유하기도, 지키기도 한다. 뛰어난 하프 솜씨의 소유자.",
        "img": "agents/chr08.png",
        "img2": "agents/chr08-1.png",
        "img3": "agents/chr08-2.png",
        "author": "세토",

        "skill1": "활력의 고동",
        "skill1b": "(15s)",
        "skill1a": "주변 아군에게 <span style='color:#FFFF00;'>힘</span>과 <span style='color:#FFFF00;'>신속</span>을 부여한다",
        "skill2": "치유의 선율",
        "skill2b": "(25s)",
        "skill2a": "주변 아군의 체력을 회복시킨다",
        "skill3": "불협화음",
        "skill3b": "(25s)",
        "skill3a": "전방으로 적에게 피해를 주고, 버프를 제거시키는 불협화음을 발사한다",
        "ultimate": "하모니",
        "ultimateb": "<{85s}>",
        "ultimatea": "선딜레이 후, 주변 모든 아군을 대량으로 회복하고 디버프를 제거한다",
        "passive": "",
        "passivea": "",

    },{ "name": "에필",
        "hanzul": "생명의 힘이 대지를 싹틔우니.",
        "num": "09",
        "role": "⭐ 지원형",
        "area": "🌿 실바네르",
        "hp": "38",
        "weapon": "장미 검",
        "story": "실바네르의 오래된 대지의 정령. 정령왕들의 중심 인물 중 하나이자, 인간들과 가장 많은 접점이 있는 정령왕 중 하나이다.",
        "img": "agents/chr09.png",
        "img2": "agents/chr09-1.png",
        "img3": "agents/chr09-2.png",
        "author": "코보",

        "skill1": "가시 덩굴",
        "skill1b": "(10s)",
        "skill1a": "전방으로 적에게 <span style='color:red;'>출혈</span>을 부여시키는 가시덩굴을 날린다",
        "skill2": "만개",
        "skill2b": "(25s)",
        "skill2a": "주변 아군에게 <span style='color:#FFFF00;'>정화</span>와 <span style='color:#FFFF00;'>저항</span>을 부여시킨다",
        "skill3": "개화",
        "skill3b": "(40s)",
        "skill3a": "전방 구역을 공격하며, 구역 안에 있는 적에게는 <span style='color:red;'>출혈</span>을 부여시키고, 자신과 아군에게 <span style='color:#FFFF00;'>재생</span>을 부여한다",
        "ultimate": "생명의 빛",
        "ultimateb": "<{80s}>",
        "ultimatea": "주변 아군에게 일시적으로 <span style='color:#FFFF00;'>무적</span>과 <span style='color:#FFFF00;'>넉백 저항</span>을 부여한다",
        "passive": "자연의 수호",
        "passivea": "피해를 입거나, 적을 일반 공격으로 공격할 시, 자신을 제외한 주변 아군의 체력을 소량 회복한다",

    },{ "name": "세렌",
        "hanzul": "내가 어디 있는지... 한번 맞춰보지그래?",
        "num": "10",
        "role": "⭐ 지원형",
        "area": "📜 알데리온",
        "hp": "28",
        "weapon": "지팡이",
        "story": "차원의 틈 사이에서 탄생한 정체를 알수없는 안개마녀. 안개를 조종해 적의 시야와 감각을 흐리는 환영술사이다.항상 상대를 지켜보고있지만 말수가 적고 필요이상으로 다가오지 않는다.",
        "img": "agents/chr10.png",
        "img2": "agents/chr10-1.png",
        "img3": "agents/chr10-2.png",
        "author": "영인",

        "skill1": "환영의 실",
        "skill1b": "(12s)",
        "skill1a": "일시적으로 <span style='color:#FFFF00;'>은신</span>을 획득하고 전방으로 돌진한다. 해당 경로에 잠시 후, 폭발하며 피해를 입히는 흔적을 설치한다",
        "skill2": "침식의 안개",
        "skill2b": "(20s)",
        "skill2a": "안개 함정을 설치한다. (최대 1개)<br>안개 함정에 닿을 시, 피해를 입고 <span style='color:red;'>실명</span>과 <span style='color:red;'>나약함</span>을 획득한다",
        "skill3": "안개화",
        "skill3b": "(30s)",
        "skill3a": "자신 또는 아군 한명에게 안개 표식을 부여한다.<br>스킬 재사용 시, 안개 표식을 가진 아군에게 <span style='color:#FFFF00;'>은신</span>을 부여하며, 해당 위치에 분신을 소환한다",
        "ultimate": "심안 붕괴",
        "ultimateb": "<{70s}>",
        "ultimatea": "자신의 분신을 3개 소환하며, <span style='color:#FFFF00;'>은신</span> 상태가 된다.<br>해당 분신은 파괴될 시 발생하는 폭발 피해량이 강해지며, 소환된 후, 2초 뒤 자동적으로 폭발한다",
        "passive": "",
        "passivea": "",

    },{ "name": "\uFFFF<span style='color:#848484;'><s>???</s></span>",
        "hanzul": "행운의 여신이 언제나 나의 편을 들고 있다고~",
        "num": "11",
        "role": "⭐ 지원형",
        "area": "❓ 불명",
        "hp": "30",
        "weapon": "잭 나이프",
        "story": "[공개되지 않음]",
        "img": "agents/missing.png",
        "img2": "agents/missing.png",
        "img3": "agents/missing-2.png",
        "author": "Original",

        "skill1": "도박",
        "skill1b": "(5s)",
        "skill1a": "50% 확률로 랜덤한 <span style='color:#FFFF00;'>버프</span>를 획득한다",
        "skill2": "밑장 빼기",
        "skill2b": "(20s)",
        "skill2a": "전방 있는 적 한명을 공격한다. 적의 버프를 강탈한다",
        "skill3": "도박장 오픈",
        "skill3b": "(45s)",
        "skill3a": "도박장을 설치하는 투사체를 던진다. 도박장은 범위 내에 있는 아군에게 <span style='color:#FFFF00;'>은신</span>을 제공한다",
        "ultimate": "풀하우스",
        "ultimateb": "<{60s}>",
        "ultimatea": "일시적으로 풀하우스 상태가 된다. 풀하우스 상태 동안 도박의 쿨타임이 50% 감소하며, 자신이 보유중인 버프를 모든 아군에게 공유한다",
        "passive": "잭팟",
        "passivea": "도박을 4연속으로 성공 시, 일시적으로 대량의 버프를 획득한다",
        
    }
]