const characters = [
    {   name: "카르티에",
        code: 17,
        hanzul: "이거 올해안에 채택 안되면 님 미래 딸 자연선택에서 거부당함",
        role: "⚔️ 돌격형",
        hp: 30,
        weapon: "레이피어",
        story: "⠀프랑스의 몰락 귀족의 검사로 자신의 귀족가 같이다니다 귀족이 죽고난후 혼자가 되어 지금은 뒷골목을 전전하는중이다",
        concept: "돌진 및 공속기반 캐릭터",
        skill1: "샤비",
        skill1b: "(5s)",
        skill1a: "전방 돌진과 함께 적에게 낮은 피해를 줍니다",
        skill2: "기사의 맹세",
        skill2b: "(20s)",
        skill2a: "자신과 주변 아군에게 <span style='color:#FFFF00;'>속공</span>과 <span style='color:#FFFF00;'>신속</span>을 주며 근처 적 한명에겐 <span style='color:red;'>피로</span>를 줍니다",
        skill3: "패링",
        skill3b: "(30s)",
        skill3a: "단한번 적의 모든 공격을 무효화합니다<br>(출혈, 맹독, 감전은 1틱만 적용된다)",
        ultimate: "Allez!",
        ultimateb: "<{45s}>",
        ultimatea: "가장 가까운 적 한명을 <span style='color:red;'>기절</span>로 만들고 자신은 스킬을 사용한 위치에 고정된다 3초후 20의 피해를 입힙니다<br>* 이스킬 사용시 1스킬 쿨타임 초기화",
        passive: "결투 신청",
        passivea: "만약 적에게 어떤 형태로든 피해를 입힐시 결투 신청 스택이 쌓입니다(최대 2스택) ",
        img: "images/chr17.png",
        day: "2025/12/27"
    },
    {   name: "하루견과",
        code: 16,
        hanzul: "하루에 한개씩 먹으면 몸이 건강해짐",
        role: "🔥 저격형",
        hp: 30,
        weapon: "캐슈넛 ㅡ 권총",
        concept: "이게 뭐야 쉬벌",
        skill1: "아몬드",
        skill1b: "(15s)",
        skill1a: "전방 7칸까지 총을 발사해 적중시 <span style='color:red;'>출혈</span>과 <span style='color:red;'>멀미</span>를 4초간 부여합니다",
        skill2: "렌틸콩",
        skill2b: "(20s)",
        skill2a: "전방 5칸까지 8발을 산탄으로 발사한다 한발당 3의 피해를 입힌다 (헤드샷 X)",
        skill3: "호두",
        skill3b: "(35s)",
        skill3a: "전방으로 호두를 던져 터뜨린 후 적중한 적에게 <span style='color:red;'>구속2</span> 2초와 <span style='color:red;'>취약</span> 6초를 부여하고 본인에겐 <span style='color:#FFFF00;'>신속2</span> 을 10초 부여합니다",
        ultimate: "Surprise mother fxxker",
        ultimateb: "<{70s}>",
        ultimatea: "주머니에서 적당한 미니건을 장착하여 12초간 난사합니다. 발당 3의 피해를 입힙니다. [초당 30발] [탄창 200발]",
        passive: "",
        passivea: "",
        img: "images/chr16.png",
        day: "2025/12/20"
    },
    {   name: "레버너",
        code: 15,
        hanzul: "이 생명은 영원하되, 결코 끝낼 수 없는 저주였다는 것을.",
        role: "⚔️ 돌격형",
        hp: 24,
        weapon: "부러진 낫",
        story: "⠀나는 본래 존재를 잊혀진 존재였소. 그렇기에 나의 존재는 무로 돌아가 아무런 의미도 남기지 못한 채 허무 속에 사라져야 했을 테오. 허나 그렇게 소멸을 맞이하던 순간, 깊은 암흑의 틈새에서 하나의 **별**이 나를 불러세웠소. 그 **별**은 내게 다가와 속삭였소. 그리고 나는 다시 되살아났소.죽음으로부터 돌아온 것이오. 허나 그것이 축복일 것이라 생각했던 나는 곧 깨닫게 되었소.",
        concept: "죽음을 트리거로 운용하는 고난이도 근접 딜러 + 암살자형 캐릭터입니다",
        skill1: "영혼 수확",
        skill1b: "(6s)",
        skill1a: "전방을 낫으로 크게 가로로 베며 적을 공격한다. 적의 체력이 20% 미만일 시, 즉사시킨다",
        skill2: "영혼 수확2인데이름을못정한",
        skill2b: "(12s)",
        skill2a: "전방을 낫으로 세로로 내려찍으며 적을 공격한다. 적 적중시, 순간적으로 자신의 방향으로 끌고온다",
        skill3: "망령화",
        skill3b: "(20s)",
        skill3a: "사용시, 잠시동안 유체화가 된다. 피해를 무효화하며, 신속하게 이동할 수 있다. 유체화 도중에는 공격과 스킬을 사용할 수 없다",
        ultimate: "소생",
        ultimateb: "<{60s}>",
        ultimatea: "스킬 발동 후, 10초 이내로 레버너가 처치될 시, 잠깐의 선딜레이 이후, 자가 부활한다. 자가 부활하는 도중 주변 적에게 큰 피해를 입힌다. 자가 부활 후, 잠시동안 무적 + 디버프 면역 상태가 되며, <span style='color:#7500A8;'>망령 스택</span>을 1 획득한다",
        passive: "망령",
        passivea: "- 최댓값: 5<br>- 전투 동안 아래의 효과를 획득합니다<br>⠀· 스킬 피해량(망령 스택 × 20) % 증가<br>⠀· 이동 속도(망령 스택 × 10) % 증가<br>⠀· 최대 체력(망령 스택 × 4) 감소",
        img: "images/chr15.png",
        day: "2025/12/13"
    },
    {   name: "테스크",
        code: 14,
        hanzul: "우리는 뭐든 믿었다 힘들었기에 믿음의 깨진자는 누구보다 간절하지 그리고 강력하다",
        role: "⭐ 지원형",
        hp: 34,
        weapon: "깨져버린 심볼 ㅡ 공격 시, 자신에게 <span style='color:#FFFF00;'>저항1</span> 1초 적용",
        story: "⠀그렇기에 나는 그들의 깨진 믿음을 심볼로 만들었고 그들의 믿음을 나의 무기로 삼았다. 하! 호구 새끼들 그리고 그들을 모두 죽였다. 그들의 믿음인 나를 깨뜨려 나를 더! 더! 강하게 만들었다!",
        concept: "사이비 교주 쉐에이끼",
        skill1: "보아라!",
        skill1b: "(13s)",
        skill1a: "자신에게 <span style='color:#FFFF00;'>신속1</span> 3초를 부여하고 투사체를 던진다 아군이 맞으면 <span style='color:#FFFF00;'>신속1</span> 4초와 <span style='color:#FFFF00;'>보호막</span> 2칸을 부여한다. 적이 맞으면 <span style='color:red;'>구속</span>을 부여하고 2칸의 피해를 입힌다",
        skill2: "강함을!!",
        skill2b: "(20s)",
        skill2a: "앞으로 한 3~4칸 전진 후 <span style='color:#FFFF00;'>신속1</span> 5초간 획득 및 <span style='color:#FFFF00;'>속공</span> 획득, 돌진하면서 지나온 길에 파티클을 뿌리며 맞은 적에게 <span style='color:red;'>독1</span>을 4초간 부여 한다",
        skill3: "나에게!!!",
        skill3b: "(30s)",
        skill3a: "주변 아군에게 <span style='color:#FFFF00;'>저항</span>과 <span style='color:red;'>구속</span>을 10초간 겁니다. 대신 자신에게 <span style='color:#FFFF00;'>힘1</span> 10초와 <span style='color:#FFFF00;'>신속1</span> 7초, 기본무기가 15초간 강화되어 저항 대신 <span style='color:#FFFF00;'>힘1</span>을 2초간 자신에게 부여합니다",
        ultimate: "믿음을 보여라!!!!",
        ultimateb: "<{50s}>",
        ultimatea: "주변 3.5칸 내의 아군과 자신에게 12초간 <span style='color:#FFFF00;'>힘1</span>과 함께 <span style='color:#FFFF00;'>신속 1</span> 5초 줍니다. 적군이 들어있으면 <span style='color:red;'>구속</span>을1을 4초간 부여 합니다.자신의 패시브가 일시적으로 강화되어 40% 에서 70% 로 커트라인이 올라갑니다.",
        passive: "더!! 더!! 많은 믿음을!!",
        passivea: "피가 50%이하로 떨어지면 40%가 될때까지 재생 1을 받는다",
        img: "images/chr14.png",
        day: "2025/12/13"
    },
    {   name: "파아뤼체",
        code: 13,
        hanzul: "파리채로 엄마한태 맞앗는데 파리 잡는부분으로 맞았는데 저 파리되는거 아닌가요? 몸이이상해요 저 파리되는거 같아요 으엉ㄴ런맹런앳ㅎㄷㅅ",
        role: "⚔️ 돌격형",
        hp: 25,
        weapon: "미니 파리채 ㅡ 낮은 확률로 <span style='color:red;'>감전</span> 부여",
        story: "⠀파라채는 평범한 사람이었으나, 어머니에게 파리 잡는 부분으로 맞은 뒤, 자신이 파리로 변해가게 되었습니다. 그는 자신의 몸이 점점 가벼워지고, 시야가 이상해지고, 짜증나는 소리가 귓가에 맴돈다고 주장합니다. 다른 요원들은 그저 정신이 불안정한 사람으로 보지만, 그의 전투 방식은 마치 짜증나는 해충처럼 예측 불가능하고 치명적입니다. 그는 자신을 때린 어머니의 파리채를 모방한 미니 파리채를 들고, 끊임없이 불안정하게 움직입니다.",
        concept: "극도의 기동성과 짜증나는 방해 효과를 가진 하이 리스크-하이 리턴형 암살자입니다",
        skill1: "순간 비행 가속",
        skill1b: "(18s)",
        skill1a: "1초 동안 자신에게 <span style='color:#FFFF00;'>신속 III</span> (이동 속도 50% 증가) 버프를 부여합니다. 사용 즉시 점프력이 2배 증가합니다.<br>추가 효과: 가속이 끝난 후, 주변의 가장 가까운 적 1명에게 1초간 <span style='color:red;'>피해 망상</span> 디버프를 부여합니다. (파리가 귓가에 맴도는 느낌이냐 으;;;;) ",
        skill2: "겹눈 시야 분할",
        skill2b: "(30s)",
        skill2a: "전방 부채꼴 범위로 얇고 투명한 진동 파동을 발사합니다. 적중한 모든 적에게 3초 동안 <span style='color:red;'>실명</span> 디버프를 부여합니다.",
        skill3: "이거 맹독인가?",
        skill3b: "(40s)",
        skill3a: "자신이 들고 있는 미니 파리채에 맹독을 묻힌다고 믿으며, 다음 3회의 기본 무기 공격에 <span style='color:red;'>맹독</span> 3초 효과를 부여합니다. (힘들면 시간으로 하셈 ㅋ)",
        ultimate: "효자손으로 맞아라!",
        ultimateb: "<{95s}>",
        ultimatea: "거대하고 낡은 '효자손' 모양의 그림자 무기를 소환하여, 전방 직선 범위에 있는 모든 대상(아군 포함)을 강하게 내려칩니다.<br>- 적중한 모든 대상은 에어본 효과와 함께 매우 큰 피해를 입고, 30초간 <span style='color:red;'>저주</span> 디버프를 받습니다.<br>- 특징: 아군에게도 피해를 주며 <span style='color:#FFFF00;'>보호막</span> 버프를 부여합니다.",
        passive: "존재감 희박",
        passivea: "피해를 입지 않은 상태로 3초간 정지해 있을 경우, 자동으로 은신 버프를 얻습니다. 다만 너무 오래 앉아있으면 윙 소리가 나기 시작합니다.<br>움직일 때마다 작게 '윙-' 소리가 따라다니며, 점프 시 매우 높게 뛸 수 있습니다(마치 파리가 점프하는 것처럼) ",
        img: "images/chr13.png",
        day: "2025/12/13"
    },
    {   name: "로레온",
        code: 12,
        hanzul: "끼ㄲ끽ㅋㅋ끽ㅋㅋㅋ끽ㅋㅋㅋ엌ㅋㅋ",
        role: "⚔️ 돌격형",
        hp: 36,
        weapon: "채찍",
        story: "⠀출입 금지된 숲에 싸들어갔다가 마녀한테 잘못걸려서 인체개조 + 이상한놈이랑 계약당해서 피가 닳지 않으면 그냥 미친 존@나 갈증이 생김 대신 피를 소모하는 만큼 강해진다",
        concept: "스킬로 피깎고 개쳐맞아서 피깎고 궁써서 피회복 반복 ㅇㅋ?",
        skill1: "채찍질",
        skill1b: "(7s)",
        skill1a: "피를 2칸 깎고 전방으로 채찍을 휘둘러 맞은 상대에게 피해를 입힌다",
        skill2: "갈증 해소",
        skill2b: "(13s)",
        skill2a: "자신의 피를 2.5칸 깎고 <span style='color:#FFFF00;'>신속</span>을 얻는다 전방 2칸 범위에 피를 뿌려 피해를 입힌다",
        skill3: "저주받은 피",
        skill3b: "(30s)",
        skill3a: "피를 <span style='color:#A4FF77;'>4칸 회복</span>하고 전방 3칸으로 피를 뿌린다 맞은 적은 5초간 <span style='color:red;'>독</span>과 <span style='color:red;'>저주</span> 상태에 빠진다.",
        ultimate: "목 축이기",
        ultimateb: "<{60s}>",
        ultimatea: "자신의 깎인 최대 체력 피에 비례한 데미지를 입힌다(60%) 적을 죽였으면 쿨타임을 15초 줄이고 피를 <span style='color:#A4FF77;'>깎인 체력에 비례해 회복</span>한다",
        passive: "돌아오는 생기",
        passivea: "체력이 낮아질수록 힘을 얻는다<br>2단계(3분의 1 감소 힘 1, 25%일때 힘 2)",
        img: "images/chr12.png",
        day: "2025/12/13"
    },
    {   name: "와세르주",
        code: 11,
        hanzul: "안녕하세요. 전 와세르주예요. 제가 고백을 너무 많이 받아서 고민이예요... 제가 지금까지 받아온 고백만 해도 789번 정도 받...",
        role: "⭐ 지원형",
        hp: 40,
        weapon: "축축한 수건 ㅡ 랜덤 확률로 <span style='color:red;'>구속 I</span> 0.5초 부여",
        story: "⠀와세르주는 원래 평범한 동네 수영장 안전 요원이었습니다. 그는 물을 좋아하고, 물 관련 안전에 극도로 집착합니다. 문제는 그 집착이 일반적인 전투 환경에서도 발현된다는 것입니다. 그는 총알이 날아다니는 전장에 안전을 확보하고, 미끄러짐을 방지하며, 습도를 조절하기 위해 파견되었습니다. 그는 자신의 임무를 매우 진지하게 수행하며, 다른 요원들이 이해할 수 없는 기준으로 ''안전하지 않은'' 구역을 지정하고 물과 미끄러움을 사용하여 모두를 곤란하게 만듭니다.",
        concept: "전투 지역을 엉망진창으로 만들고, 모두를 불편하게 만드는 지역 장악형 지원가입니다",
        skill1: "긴급! 물바닥 생성!",
        skill1b: "(15s)",
        skill1a: "지정한 위치에 좁은 원형 범위로 물을 분사하여 4초 동안 '젖은 바닥' 지역을 생성합니다.<br>- '젖은 바닥' 위에 있는 모든 적군은 <span style='color:red;'>구속 I</span> 디버프를 받습니다.<br>- '젖은 바닥' 위에 있는 모든 아군이 이동을 시작할 때, 미끄러집니다.<br>- 와세르주 본인은 '젖은 바닥'에서 이동 속도가 5% 증가합니다.",
        skill2: "안전 레인 설치",
        skill2b: "(25s)",
        skill2a: "전방으로 얇고 긴 안전선 (부표가 달린 로프)을 직선으로 던져 설치합니다. 이 로프는 10초 동안 유지되며, 로프를 통과하는 아군에게 2초간 <span style='color:#FFFF00;'>신속</span> 버프를 부여합니다.<br>- 적군이 로프를 통과할 때, <span style='color:red;'>피해 망상</span> 디버프를 1초 부여하며 (+아무거나 알아서 짜셈) ''위험합니다!''라는 와세르주의 텍스트가 출력됩니다.",
        skill3: "물놀이 금지! (강제 퇴장)",
        skill3b: "(45s)",
        skill3a: "강력한 수압을 가진 물줄기를 전방 좁은 부채꼴 범위로 발사합니다. 적중한 적은 2의 피해와 함께 강력한 에어본 및 뒤로 밀쳐내기 효과를 받습니다. 이 스킬은 오직 적을 벽이나 장애물에 충돌시키는 용도입니다. (적중 피해가 매우 낮음) 충돌에 성공하면 적에게 3초간 <span style='color:red;'>기절</span> 디버프를 부여합니다. (단, 충돌하지 않으면 효과 없음)(만들기 어려우면 하지마셈 ㅋ) ",
        ultimate: "긴급!!! 오리발 착용!!",
        ultimateb: "<{90s}>",
        ultimatea: "와세르주가 즉시 5초 동안 거대한 오리발을 착용합니다. 오리발을 착용하는 동안 와세르주는 다음과 같은 효과를 얻습니다.<br>- 자신에게 <span style='color:#FFFF00;'>'개빠른 신속'</span> (이동 속도 30% 증가) 버프 부여, 자신은 '구속 면역'이 됨<br>- 기본 무기(축축한 수건)의 공격 속도가 2배 증가하고, 적중 시 부여하는 <span style='color:red;'>구속 I</span> 디버프가 ** <span style='color:red;'>구속 II</span>(이동 속도 20 % 감소)로 강화됩니다.<br>- 오리발 착용 중 와세르주는 오직 S자형으로만 이동할 수 있습니다. (직선 이동 불가, 모든 이동은 좌우로 흔들리며 움직여야 함 혹은 알아서). 이로 인해 정확한 조작과 예측 가능한 움직임이 불가능해집니다.<br>- 궁극기 발동 중에는 계속해서 물속에서 헤엄치는 듯한 첨벙거리는 효과음이 발생하여 적에게 위치를 쉽게 노출시킵니다.",
        passive: "완벽한 접지력",
        passivea: "와세르주는 '미끄러움' 디버프에 면역입니다",
        img: "images/chr11.png",
        day: "2025/12/13"
    },
    {   name: "롤랜드",
        code: 10,
        hanzul: "내게는 고통밖에 없습니다.",
        role: "⚔️ 돌격형",
        hp: 30,
        weapon: "단검 ㅡ <span style='color:red;'>출혈</span> 2초 부여",
        story: "⠀어렸을때 실험실로 팔려나가 여러 강화시술을 받게되어 덩치가 크지는 않지만 강한편 암살 특화(단검사용)",
        concept: "평타 혹은 스킬 사용으로 출혈을 붙인 뒤 스킬을 사용하여 여러 디버프를 붙이는 형식",
        skill1: "베어내기",
        skill1b: "(8s)",
        skill1a: "전방의 적에게 6대미지와 <span style='color:red;'>출혈</span> 5초를 부여한다",
        skill2: "단검투척",
        skill2b: "(15s + 다음타 3초)",
        skill2a: "원거리 무기를 투척 후 <span style='color:red;'>구속1</span> 부여 다음타 적중시 <span style='color:red;'>출혈1</span> 7초 부여",
        skill3: "각보",
        skill3b: "(30s)",
        skill3a: "전방 3칸앞으로(돌진ㄴㄴ) 공격 후 적중시 3스킬의 쿨타임이 5초 줄어든다 적은 <span style='color:red;'>출혈 2, 6초</span>와 4의 피해를 입힌다",
        ultimate: "과다출혈",
        ultimateb: "<{60s}>",
        ultimatea: "전방 3칸 앞 상대방에게서 출혈을 제거 후 <span style='color:red;'>멀미, 실명, 침묵</span>을 부여한 후 8의 피해를 입힌다(출혈이 없다면 <span style='color:red;'>출혈 1</span>을 10초간 부여한다)",
        passive: "고조되는 감정",
        passivea: "피가 절반 이하로 줄어들면 신속 1을 얻음",
        img: "images/chr10.png",
        day: "2025/12/13"
    },
    {   name: "라그나",
        code: 9,
        hanzul: "후후... 모두들 집중!! 이 몸이 왔노라!!",
        role: "🔥 저격형",
        hp: 28,
        weapon: "석궁 ㅡ 빠른 장전 1~2",
        story: "⠀[ 노르하임 외각 지역 탐사 보고서 ] - 폭설 이상 현상 조사) 수년간 지속된 노르하임 외곽의 비정상적 폭설 현상 조사 진행. 다수의 시신이 발견된 오두막에서 생존자 1명 구조. 생존자는 과거 노르하임 외곽 마을의 사냥꾼 “라그나” 로 확인됨. 확인되지 않은 종족과의 혼혈로 추정되며, 정밀 조사는 추후 진행 예정. 폭설 사태 중 양쪽 눈을 상실했으나, 청각·후각 및 공간 지각 능력이 비정상적으로 발달해 활동에는 큰 제약이 없음.특히 피 냄새를 감지하는 능력이 뛰어남. 신체적 외상은 경미하나, 정신적 불안정성이 관찰됨. 탐사 인원 전원의 합의 하에 치료를 위해 커스텀 컴퍼니 본부로 이송 결정.",
        concept: "실명 기믹이 첨가된 깡스팩 높은 원딜러",
        skill1: "해체",
        skill1b: "(7s)",
        skill1a: "전방의 적에게 피해를 주고 넉백시키며 <span style='color:red;'>출혈</span>을 부여한다",
        skill2: "먹잇감 포착",
        skill2b: "(25s)",
        skill2a: "전방으로 적에게 피해와 <span style='color:red;'>출혈</span>을 부여하는 화살을 5발 연속적으로 발사한다 (한조e)",
        skill3: "피냄새",
        skill3b: "(25s)",
        skill3a: "출혈이 부여된 모든 적에게 일시적으로 <span style='color:red;'>발광</span>을 부여한다.",
        ultimate: "사냥감 추적",
        ultimateb: "<{80s}>",
        ultimatea: "약간의 선딜레이 이후, 전방으로 매우 빠른 투사체 속도를 지닌 투창을 던진다. 적에게 적중 시, 평타 정도의 피해를 입히며 <span style='color:red;'>꿰뚫은 투창</span> 디버프를 영구 부여한다. <span style='color:red;'>꿰뚫은 투창</span>을 가진 적이 생존해있는 동안, 궁극기 쿨타임이 돌아가지 않는다<br><br>꿰뚫은 투창:<br>받는 피해량이 1.25배 증가한다 (취약과 합연산으로 작동된다) 출혈이 부여되지 않은 상태여도, <span style='color:red;'>출혈 판정</span>으로 취급된다. 영구적으로 <span style='color:red;'>발광</span>에 걸린다.",
        passive: "초감각",
        passivea: "해당 캐릭터는 <span style='color:red;'>제거 불가능한 실명</span> 디버프를 영구적으로 획득한다.<br>다음 조건이 성립된 적에게 발광을 매우 잠깐 부여한다.<br>• 라그나의 공격에 의해 피해를 받음<br>• 라그나의 주변 반경 5m 안으로 접근<br>• 10 이상의 큰 피해를 입음<br>• 탄환을 발사하는 스킬 사용<br>• 궁극기 사용",
        img: "images/chr09.png",
        day: "2025/12/10"
    },
    {   name: "크레머",
        code: 8,
        hanzul: "서처 배포. 일단 이것부터 디버깅하자.",
        role: "⭐ 지원형",
        hp: 28,
        weapon: "크레나의 눈물 ㅡ 적 타격 및 파괴될 시, 스킬 영구 봉인",
        story: "⠀4197년 사이버펑크 세상속에서 활동하는 해킹범으로 전세계에서 수배중인 인물이다.",
        concept: "여러가지 기능을 수행하는 드론으로 지역 장악 및 원거리 견제가 가능하다",
        skill1: "searcher",
        skill1b: "(3s)",
        skill1a: "대상을 추적하는 드론을 날린다. 드론이 대상을 찾으면 대상에게 <span style='color:red;'>발광</span>과 <span style='color:red;'>실명</span>을 부여하고 파괴된다. (단 드론은 원거리 사격 등으로 제거가 가능하다)",
        skill2: "debugger",
        skill2b: "( 10s )",
        skill2a: "패시브 활성화 후 사용할 수 있다. 적에게 <span style='color:red;'>저주</span>를 부여한다.",
        skill3: "refactor",
        skill3b: "(35s)",
        skill3a: "패시브 활성화 후 사용가능하다. 적에게 refactor드론 5대를 보내 폭격한다.",
        ultimate: "Solver",
        ultimateb: "<[ 일회용 ]>",
        ultimatea: "서든데스에 들어가고 사용이 가능하다. 사용시 적에게 두번의 <span style='color:red;'>발광</span> 효과를 준다. 그 후 대상에게 1번 즉사에 가까운 데미지를 준다. 사용 후 자신의 기본 무기가 파괴된다.",
        passive: "정보의 귀재",
        passivea: "적들이 발광에 걸리면 스킬 2와 3이 해금된다.",
        img: "images/chr08.png",
        day: "2025/12/09"
    },
    {   name: "호위 무사",
        code: 7,
        hanzul: "아씨의 명을 받들어, 호위하겠습니다.",
        role: "⭐ 지원형",
        hp: 46,
        weapon: "검",
        story: "⠀**사내 하나가 잔을 기울이며 혀를 차며 말하되…** “에구구… 세상사 한 치 앞도 모르는 법이여. 15년 전 그날 밤을 생각하면 아직도 등골이 서늘허다네. 궁궐 안에서 갑자기 칼부림이 일어나고, 임금이니 중전이니, 핏줄까지 모조리 쓰러졌다는 말이 아닌가.” 다른 사내가 주변을 한 번 훑어보고 목소리를 낮추어 받거늘, “쉿— 그 얘긴 지금도 조심해야 하네. 헌데 말이여… 그날 밤, 딱 한 줄기 목숨이 빠져나갔다 하더군.” (생략)",
        concept: "1인 케어형 탱포터입니다. 호위 기믹으로 아군 한명을 전적으로 케어하면서 든든하게 지원해주는 캐릭터입니다.",
        skill1: "적진 주파",
        skill1b: "(8s)",
        skill1a: "전방을 크게 베며 적을 공격한다. 적중 시, 자신과 <span style='color:#00AEFF;'>호위</span> 대상에게 약간의 <span style='color:#FFFF00;'>보호막</span>을 부여한다",
        skill2: "호위",
        skill2b: "[ ON/OFF ]",
        skill2a: "가장 가까운 아군 한명을 <span style='color:#00AEFF;'>호위</span>한다. 스킬 재사용 시, <span style='color:#00AEFF;'>호위</span> 상태가 해제된다.",
        skill3: "태세 변환",
        skill3b: "(10s)",
        skill3a: "자신의 태세를 변환한다 (상시 적용) ( 호위 태세 <-> 원호 공격 )<br>• 호위 태세<br>⠀- <span style='color:#00AEFF;'>호위</span> 중인 대상과 자신에게 <span style='color:#FFFF00;'>저항</span> 버프를 부여한다<br>⠀- <span style='color:#00AEFF;'>호위</span> 중인 대상이 받는 피해를 호위 무사와 나눠 받는다<br>⠀- ex) A가 10의 피해를 입을 시, A와 호위 무사가 각각 4의 피해를 나눠 받음<br>• 원호 공격<br>⠀- <span style='color:#00AEFF;'>호위</span> 중인 대상과 자신에게 <span style='color:#FFFF00;'>신속</span>과 <span style='color:#FFFF00;'>속공</span> 버프를 부여한다",
        ultimate: "내가 너만큼은 반드시 살려주마.",
        ultimateb: "<{80s}>",
        ultimatea: "<span style='color:#00AEFF;'>호위</span> 대상에게 이동한 후, 일정 시간 동안 <span style='color:#00AEFF;'>호위</span> 대상을 <span style='color:#FFFF00;'>무적</span>으로 만든다. 호위 무사가 사망할 시, 무적 상태가 해제된다. 호위 대상이 존재해야만 사용 가능하며, 자신 밖에 생존하지 않았다면 이 스킬이 아래의 스킬로 변경된다<br><br>이름못정했다 <{ 80s }><br>⠀-일정 시간 동안 <span style='color:#FFFF00;'>힘</span>과 <span style='color:#FFFF00;'>신속</span> 버프를 획득한다. 1스킬의 쿨타임이 2초로 감소한다",
        passive: "",
        passivea: "",
        img: "images/chr07.png",
        day: "2025/12/09"
    },
    {   name: "케르디아",
        code: 6,
        hanzul: "피할 수 없는 싸움이라면, 내가 받아내지.",
        role: "⚔️ 돌격형",
        hp: 48,
        weapon: "타마르고의 검",
        story: "⠀과거 케르빈에 출연한 드래곤을 무찌른 전설의 용사, 전설 속에선 우리엘의 대리자로 전해져 온다.",
        concept: "지속적인 싸움을 해야하는 탱브루저, 싸움의 시간이 길어질수록 점점 강해진다.",
        skill1: "존하우",
        skill1b: "(6s)",
        skill1a: "길게 사선으로 베어낸다. 대상이 존하우를 맞으면 존하우의 쿨타임이 초기화된다.",
        skill2: "클레이모어",
        skill2b: "(25s)",
        skill2a: "바라보는 방향에서 오는 모든 공격을 막는다. 상대의 공격이 막히면 2칸 돌진하여 대상을 <span style='color:red;'>기절</span>시킨다.",
        skill3: "옥스",
        skill3b: "(30s)",
        skill3a: "패시브가 3초 이상 중첩시 사용 가능하다. 사용시 옥스 자세를 잡는다(자체 기절) 옥스 자세 중 <span style='color:#FFFF00;'>저항3</span>과 <span style='color:#A4FF77;'>재생2</span>가 부여된다. 바라보는 방향에서 공격해오면 대상의 공격을 막고 기절에서 풀린다.",
        ultimate: "천상의 투기장(발할라)",
        ultimateb: "<{60s}>",
        ultimatea: "패시브가 17초 이상일때 사용 가능하다. 사용시 대상과 자신을 발할라로 데려간다. 발할라는 13초 동안 지속되며 둘 중 한명이 발할라에서 죽는다면 발할라를 시전한 / 시전당한 위치로 돌아온다.",
        passive: "인내의 기사",
        passivea: "전투가 지속됨에 따라 패시브시간을 얻는다. 패시브 시간을 중첩하여 다음과 같은 버프를 얻는다. <br>• 10초 - 저항<br>• 15초 - 속공<br>• 20초 - 힘<br>• 40초 - 상시 정화 및 극대화된 저항, 힘, 속공",
        img: "images/chr06.png",
        day: "2025/12/08"
    },
    {   name: "레미",
        code: 5,
        hanzul: "메인 디쉬 나갑니다~!!",
        role: "⭐ 지원형",
        hp: 24,
        weapon: "뒤집개 ㅡ 접대 상태라면 추가 피해",
        story: "undefined",
        concept: "서포팅 및 디버퍼. 궁으로 버프얻어서 팀원에게 주거나 자신이 받아먹기 가능",
        skill1: "서빙",
        skill1b: "(10s / 15s)",
        skill1a: "주변 아군및 자신에게 접시에 담겨있는 <span style='color:#FFFF00;'>버프</span>가 적용되며 3스킬 사용후 1스킬 사용시 5초의 추가 쿨타임이 생긴다.",
        skill2: "디저트",
        skill2b: "(25s)",
        skill2a: "가장 최근 사용한 <span style='color:#FFFF00;'>버프</span>/<span style='color:red;'>디버프</span>를 오른쪽 접시에 배치한다<br>(만약 접시 2개가 모두 차있는경우 사용불가.)",
        skill3: "데코레이션",
        skill3b: "(35s)",
        skill3a: "자신의 접시의 가장 왼쪽의 <span style='color:#FFFF00;'>버프</span>/<span style='color:red;'>디버프</span>의 효과를 2로 올려준다 힘 1- > 힘 2<br>ex) 3스킬 사용후 1스킬 사용시5초의 추가 쿨타임이 생긴다.",
        ultimate: "메인 디쉬",
        ultimateb: "<{10s}>",
        ultimatea: "모든 <span style='color:#FFFF00;'>버프</span> <span style='color:red;'>디버프</span>를 최대 2개까지 저장가능 사용시 접시에 <span style='color:#FFFF00;'>버프</span>/<span style='color:red;'>디버프</span>의 이름이 들어가며 확률은 반반이다. 모든 <span style='color:#FFFF00;'>버프</span>/<span style='color:red;'>디버프</span>는 1로 주어진다.",
        passive: "접시",
        passivea: "자신에 체력 위 _ _<-이런 형태의 접시라는것이 뜸 여기에 궁 사용시 버프/디버프가 접시에 올라감 왼쪽부터 차며 스킬 사용시 1번접시는 파기되며 3번접시가 들어온다<br>예) 힘    나약함<- 이상황에선 궁사용 불가 왼쪽이 우선으로 나가며 힘사용시 궁을 사용하여 새로운 버프 / 디버프를 충당할수있음",
        img: "images/chr05.png",
        day: "2025/12/08"
    },
    {   name: "스팅",
        code: 4,
        hanzul: "독도 약이 되고, 상처도 다시 피어나죠.",
        role: "⭐ 지원형",
        hp: 25,
        weapon: "가시나무 ㅡ <span style='color:red;'>출혈</span> 1초 부여",
        story: "⠀왕국 외곽 마을에 살던 스팅은 부모님이 편찮으셔서 약초를 구하기 위해 마을에서 조금 떨어져있는 금지된 숲으로 향하였고, 그곳에서 가시 덩쿨에 찔리게 되었다. 가시 덩쿨에는 독이 있었고 독에 당한 스팅은 잠시 쓰러졌다. 깨어난 스팅 오른팔에는 가시 덩쿨이 감겨져 있었고 가시나무 지팡이를 들고 있었다.왼팔에는 성스러워 보이는 문양이 그려져 있었다.",
        concept: "한의원 - 독이랑 치유를 자유자제로 다룸",
        skill1: "가시나무 휘뿌리기",
        skill1b: "(15s)",
        skill1a: "전방으로 가시나무를 휘뿌려서 철질려처럼 바닥에 설치, 데미지는 열매 덩쿨처럼 밟으면 1 뎀, 적에게는 <span style='color:red;'>맹독</span> 4초를 팀원에게는 <span style='color:#A4FF77;'>피 7 회복</span>",
        skill2: "도핑",
        skill2b: "(20s)",
        skill2a: "자신의 <span style='color:#A4FF77;'>피를 6 회복</span>하고 <span style='color:#FFFF00;'>신속2</span> 부여한다.",
        skill3: "가시나무 던지기",
        skill3b: "(25s)",
        skill3a: "둥근 가시나무를 힘껏 던진다. 피격 시 <span style='color:red;'>맹독</span>을 부여한다. 옵치 아나처럼 팀원이 피격 시 <span style='color:#A4FF77;'>피 8 회복</span>과 디버프 제거",
        ultimate: "가스 살포",
        ultimateb: "<{40s}>",
        ultimatea: "바이퍼 마냥 주변에 가스를 살포하는데 가스가 자기 주변 캐릭터 기준 적당한칸으로 가스가 있음. 지속시간은 10초이고 들어오면 독뎀이 들어오고 팀원은 <span style='color:#A4FF77;'>초당 피 1.5 회복</span>(찾아보니까 재생 레벨 3이 초당 1.6임)",
        passive: "맹독 가시",
        passivea: "맞은 공격 데미지 일부 반사",
        img: "images/chr04.png",
        day: "2025/12/08"
    },
    {   name: "개스코인",
        code: 3,
        hanzul: "…후. 피를… 더…!",
        role: "⚔️ 돌격형",
        hp: 34,
        weapon: "장송의 칼 ㅡ <span style='color:red;'>혈기</span> 스택 +2",
        story: "undefined",
        concept: "혈기 스택을 쌓고 터트리거나 자신에게는 버프를 주는 딜러",
        skill1: "작살 던지기",
        skill1b: "(3s)",
        skill1a: "무기를 던지고 다시 돌아오게 한다 <span style='color:red;'>혈기</span> 스택+3<br>ex) cwc 그 무기던지는 새끼",
        skill2: "회전격",
        skill2b: "(24s)",
        skill2a: "무기를 회전시켜 데미지를 광역으로 줌 <span style='color:red;'>혈기</span> 스택+27<br>ex) 다리우스 q스킬 느낌",
        skill3: "파열",
        skill3b: "(60s)",
        skill3a: "30/60/90스택처럼 30의 배수로 <span style='color:red;'>혈기</span> 스택을 모두 터트린다<br>(44스택이하는 30스택데미지, 45스택이상은 60스택데미지) ",
        ultimate: "혈월",
        ultimateb: "<{65s}>",
        ultimatea: "전방에 넓은 범위로 공격하고 적중시 아군적군 상관없이 에어본상태, <span style='color:red;'>혈기</span> 스택+40",
        passive: "아수라장",
        passivea: "개인전 ㅡ 누적 100스택당 랜덤 버프 1<br>팀전 ㅡ 누적 150스택당 랜덤 버프 1",
        img: "images/chr03.png",
        day: "2025/12/08"
    },
    {   name: "녜힁",
        code: 2,
        hanzul: "근디 젠쇼완아… 나를 막을라믄 그 양식을 싸게싸게 뽑았어야제!",
        role: "⚔️ 돌격형",
        hp: "매우 높음",
        weapon: "천태선도 ㅡ <span style='color:#910700;'>탄환</span> 소모",
        story: "⠀서부 염지 에이지사의 쿼드라. 서부십검 중 하나",
        concept: "스킬 사용시 총알을 소모하며, 조건주 폭딜을 넣을 수 있음",
        skill1: "만(慢)",
        skill1b: "(30s)",
        skill1a: "10초간 달빛의 고리를 자신의 무기에 휘감는다. 자신에게 힘이 부여된다.",
        skill2: "폭새참(爆塞斬)",
        skill2b: "(12s / <span style='color:#910700;'>탄환</span> 1 소모)",
        skill2a: "약 세 블록 정도 돌진 후 적을 베어낸다",
        skill3: "쾌도난마(快刀亂麻)",
        skill3b: "(25s / <span style='color:#910700;'>탄환</span> 2 소모)",
        skill3a: "잠시동안 경직되었다가 빠르게 앞으로 돌진하며 적을 공격한다",
        ultimate: "느그들 호랑이를 잡을라그랬으믄, 느그들도 잡아맥힐 각오를 했어야제",
        ultimateb: "<{60s}>",
        ultimatea: "잠깐의 경직 후 점프하여 내리찍으며 베고, 뒤로 이동해 베고, 다시 앞으로 와 두 번 벤 뒤 마지막으로 강하게 종으로 벤다",
        passive: "탄환: 녜힁",
        passivea: "<span style='color:#910700;'>탄환</span> 12발이 지급되며, 특정 스킬에 소모된다. 모두 사용 시, <span style='color:#910700;'>맨홀표탄</span>으로 8발을 재장전한다",
        img: "images/chr02.png",
        day: "2025/12/07"
    },
    {   name: "샤렌",
        code: 1,
        hanzul: "히히! 폭발이다 폭발!!!",
        role: "⚔️ 돌격형",
        hp: 24,
        weapon: "화약 검",
        story: "⠀그녀는 평소에 테러를 하다 감옥에 잡혀버렸으나 탈옥을 하고 쫒기던 중 자신을 숨겨주는 대신 직원으로 일을 하는것으로 들어오게 되었습니다",
        concept: "인파이팅형 원딜러 (기동성으로 데미지를 넣으며 잡는 캐릭)",
        skill1: "봄버 불릿",
        skill1b: "(10s)",
        skill1a: "전방으로 0.5초 뒤에 터지는 폭탄 3개를 던지고(개당 데미지 1) 후방으로 3칸 도약한다.",
        skill2: "봄버 점프",
        skill2b: "(10s)",
        skill2a: "후방에 폭탄을 던지고 (데미지 3)자신을 밀어내며 3칸 돌진한다.",
        skill3: "붐샷",
        skill3b: "(20s)",
        skill3a: "벽,적,바닥에 붙는 1.5초뒤에 터지는점착 폭탄을 던진다. 부착 데미지 2 폭발 데미지 3",
        ultimate: "봄버 타임",
        ultimateb: "<{60s}>",
        ultimatea: "20초동안 데미지를 넣는 만큼 쿨타임 감소를 한다.<br>(ex 데미지 3을 넣으면 q w e f 스킬 쿨타임 3초 감소)",
        passive: "화약 폭발",
        passivea: "평타를 치면 5초 동안 그 플레이어에게 화약 표식을 입히고, 화약 표식이 있는 적에게 스킬 피해를 입히면 대상에게 추가 데미지 5를 입히고 1,2,3 스킬의 쿨타임을 4초 줄인다. (표식 제거)",
        img: "images/chr01.png",
        day: "2025/12/07"
    },
]